### ISSUE TITLE
PS2Alerts 3.0 integration

### ISSUE THREAD

**Issue by Maelstrome26** [kurtextrem/PS2Alerts#15]
Hey bud, long time no see.

I've recently updated PS2Alerts to real time, and it'll require done changes on both my and and yours.

I've converted everything to websockets, for real time communication. I'm wondering whether it's possible to have real time updates for the chrome plugin as well?

I've also got a wealth more of information concerning combat, not sure if that's of any use to you.

**Comment by Maelstrome26** [comment]
Hey dude, real sorry I've not got back recently, I've been extremely busy with Planetside Battles etc.

I'm going to try and get the API finished this weekend. Have your requirements changed?

**Comment by kurtextrem** [comment]
No worries and no, they're still the same.

**Comment by Maelstrome26** [comment]
Ok so to get this correct, you need the ability to see all active alerts and territory statuses, along with links to the website?

**Comment by kurtextrem** [comment]
Yep.

**Comment by kurtextrem** [comment]
Any progress? :)

**Comment by kurtextrem** [comment]
By the way:

> As part of transforming from SOE to Daybreak Games we are changing our domain names.  The domains census.soe.com and data.soe.com are going away and the new domain is census.daybreakgames.com. 
> Please reconfigure your apps to replace census.soe.com and data.soe.com with census.daybreakgames.com!
> The existing census.soe.com and data.soe.com will be turned off on April 30th 2015. We will no longer own the soe domain so we cannot continue to handle requests after April 30th.

**Comment by Maelstrome26** [comment]
Yeah I noticed that, good they told us at least.

I'm still heavily engaged with Planetside Battles, however the changes I've
made will mean that I don't need to be present at server smashes myself any
more, and staff will be able to create their own streaming pages too
automatically, which reduces my workload significantly.

I'll be spending this 4 day weekend polishing that system off, and will
hopefully mean I can get back to PS2Alerts. I've not been giving it the
attention it deserves lately :-(

I thank you for your patience though :-) it's just been real busy lately.

**Comment by Maelstrome26** [comment]
I've finally got round to starting the API. Sorry it's been taking so long, I had a massive backlog with Planetside Battles that I had to deal with.

I'll give you some docs soon :-)

**Comment by Maelstrome26** [comment]
Details of what I plan to make available: http://redd.it/346wg7

**Comment by kurtextrem** [comment]
That sounds good. As last time: it would be the best to include detailed
alert information (like what is the goal for example) in the server api so
I don't have to make multiple requests.

Also, I have my A level exams currently, which will be over in one month.
Once they're done (and the API is done as well)  I'll start updating :-)
Am 28.04.2015 21:56 schrieb "Matthew Cavanagh" <notifications@github.com>:

**Comment by Maelstrome26** [comment]
Hey man,

I've now made the Active Alerts API. Here is a sample:

```
{
  "1": {
    "status": "inactive"
  },
  "10": {
    "resultID": "6864",
    "instanceID": "5267",
    "world": "10",
    "zone": "2",
    "started": "1430761899",
    "endtime": "1430769099",
    "type": "1",
    "controlVS": "34",
    "controlNC": "38",
    "controlTR": "27",
    "status": "active"
  },
  "13": {
    "resultID": "6865",
    "instanceID": "5311",
    "world": "13",
    "zone": "4",
    "started": "1430766041",
    "endtime": "1430773241",
    "type": "4",
    "controlVS": "34",
    "controlNC": "21",
    "controlTR": "44",
    "status": "active"
  },
  "17": {
    "resultID": "6863",
    "instanceID": "5212",
    "world": "17",
    "zone": "8",
    "started": "1430761573",
    "endtime": "1430768773",
    "type": "2",
    "controlVS": "27",
    "controlNC": "27",
    "controlTR": "44",
    "status": "active"
  },
  "19": {
    "status": "inactive"
  },
  "25": {
    "status": "inactive"
  }
}
```

**Comment by Maelstrome26** [comment]
oops :P

**Comment by Maelstrome26** [comment]
I'll PM you a API key to use, I'll write up some documentation later, but it's a pretty simple request.

Heres the format you need to send requests in:

```
http://api.ps2alerts.com/v1/servers/active/{SERVERID}?apikey={APIKEY}
```

eg
```
http://api.ps2alerts.com/v1/servers/active/all?apikey=12345
```

ServerIDs supported are:
```
1: Connery
10: Miller
13: Cobalt
17: Emerald
19: Jaeger
25: Briggs
all: All servers returned
```

I suspect you'll be using the all request :)

**Comment by kurtextrem** [comment]
Will start working on the extension this weekend or probably one or two
weeks later.

Thanks again.


- Jacob

2015-05-04 21:08 GMT+02:00 Matthew Cavanagh <notifications@github.com>:

**Comment by Maelstrome26** [comment]
All working, good work dude :)
