### ISSUE TITLE
Server list still showing Ceres, Woodman and an Undefined server

### ISSUE THREAD

**Issue by Maelstrome26** [kurtextrem/PS2Alerts#19]
Hey bud,

The server list is still showing the merged servers, along with an Undefined server.

**Comment by Maelstrome26** [comment]
Is correct in the options though.

**Comment by kurtextrem** [comment]
Which version do you have installed?

**Comment by Maelstrome26** [comment]
0.9, I did a force update.

**Comment by kurtextrem** [comment]
I can confirm the issue. A clean (re)install "solves" it.

I'll probably add a version check, which does the upgrade "cleanup".

2015-05-11 11:53 GMT+02:00 Matthew Cavanagh <notifications@github.com>:

> 0.9, I did a force update.

**Comment by Maelstrome26** [comment]
Fix confirmed, that does indeed clean it. Although not everyone will think to do that and may end up uninstalling and never reinstalling :(
