### ISSUE TITLE
Extension seems broken

### ISSUE THREAD

**Issue by Maelstrome26** [kurtextrem/PS2Alerts#21]
Hey man,

I've double checked my API, and all seems to be working on this end. The Extension isn't showing any alerts, when there is clearly some on.

Any chance you could check it?

**Comment by kurtextrem** [comment]
I have no clue what went wrong. However, I have recreated the cronjob... Let's see.
Do you have any idea how long it's been broken now?

**Comment by Maelstrome26** [comment]
Must have been a couple of weeks now. I figured it was me screwing up the API and didn't have chance to check properly until recently, but it was all good my end.

**Comment by kurtextrem** [comment]
Seems like it was the cronjob failing to resume after my hoster had problems for a day.
