### ISSUE TITLE
App is buggy again

### ISSUE THREAD

**Issue by Maelstrome26** [kurtextrem/PS2Alerts#23]
Hey,

It seems that the app somehow broke. I've not done much with the active alerts API endpoint, so I'm unsure what's occurred here really.

**Comment by kurtextrem** [comment]
It stopped calling the refresh url, again.

**Comment by kurtextrem** [comment]
I started using my own crontab now, let's see how that works out.

**Comment by Maelstrome26** [comment]
Seems to be working good so far :)

**Comment by kurtextrem** [comment]
Great, so it seems like moving to my own cronjobs was a good idea.
