### ISSUE TITLE
PS2Alerts API V2 Compatability

### ISSUE THREAD

**Issue by Maelstrome26** [kurtextrem/PS2Alerts#24]
Hi Kurtextrem,

I've recently had some server troubles, so had to flatten it. As part of this flattening, I decided to create the new server with PHP7, but for some reason the API V1 is incompatible with PHP7.

Therefore, I'm currently developing a new API for PS2Alerts, written much better than the old one. API V1 is dead, and the whole site is down right now while I re-write the API.

I've already got the Active Alerts up and running, as well as basic Result information locally, I've not deployed it as of writing just yet.

I'm still working on the authorization system, so the authentication methods may change, however for now we'll probably just still use query strings, unless I decide to make the entire request process a POST system.

Heres the new endpoint you'll need to use to get the active alerts:

`http://api.ps2alerts.com/v2/alert/active` - All alerts that are currently running
`http://api.ps2alerts.com/v2/alert/active/{SERVERID}` - All alerts that are currently running on a server

There is a slight difference from the previous version, where it only returns currently running alerts, it doesn't give you a status for each server individually any more.

Also, if there is no alert on the server(s), the API will return HTTP status code `204 (empty)` the body will also be empty.

Example response:
```json
[
  {
    "ResultID": 17240,
    "instanceID": 1213,
    "ResultStartTime": 1450573535,
    "ResultEndTime": null,
    "ResultDateTime": null,
    "ResultServer": 2000,
    "ResultTimeType": "MOR",
    "ResultMajority": 0,
    "ResultWinner": "",
    "ResultDraw": null,
    "ResultAlertCont": 4,
    "ResultAlertType": 4,
    "ResultDomination": null,
    "Valid": null,
    "InProgress": 1,
    "event": 0
  },
  {
    "ResultID": 17241,
    "instanceID": 6537,
    "ResultStartTime": 1450576704,
    "ResultEndTime": null,
    "ResultDateTime": null,
    "ResultServer": 1,
    "ResultTimeType": "PRI",
    "ResultMajority": 0,
    "ResultWinner": "",
    "ResultDraw": null,
    "ResultAlertCont": 6,
    "ResultAlertType": 3,
    "ResultDomination": null,
    "Valid": null,
    "InProgress": 1,
    "event": 0
  }
]
```

If you want to get the current map status, you'll need to send a separate API request:

`http://api.ps2alerts.com/v2/metrics/map/{RESULTID}/latest`

Example response:

```json
[
  {
    "dataID": 2666364,
    "resultID": 17240,
    "timestamp": 1450573537,
    "facilityID": 287120,
    "facilityOwner": 2,
    "facilityOldOwner": 3,
    "durationHeld": 5222,
    "defence": 0,
    "controlVS": 34,
    "controlNC": 43,
    "controlTR": 18,
    "zone": 4,
    "world": 2000,
    "outfitCaptured": 0
  }
]
```

**The above API endpoint may return a 204 if no captures have occurred yet**

Note, the above request is cached for 60 seconds on a per-alert basis. I know your app will be making a lot of requests for updates on this particular request :-)

By the way, if you wanna keep track of the API development, I've open sourced it, and you can find it at: https://github.com/Maelstrome26/ps2alerts-api

**Comment by Maelstrome26** [comment]
Oh just to note, this isn't live yet, I figured I've give you some lee-way time to figure things out your end while I get the rest of the API running again.

**Comment by kurtextrem** [comment]
Currently unsure what ResultTimeType, ResultTimeType and ResultMajority means.

Do I still need an API key?

**Comment by Maelstrome26** [comment]
Here's an explanation:

ResultTimeType is a rough guide to show what kind of prime time the alert is. So I've got a set of times in my collection script, which compares the time is the alert start against these times. 

I believe it's set up in the following way:

01:00-11:59: MOR
12:00-16:59: AFT
17:00-00:59: PRI (Prime time) 

May be useful to display on your app, not sure. 

The ResultMajority field was a throwback from the days where alerts were competitive based, where your had to prevent the dominant empire to who started off with the most territory from keeping that lead. The alert type was soon phased out since all it resulted was double teaming. 

I'll go through the collection script and make sure any reference to that field is gone and delete it. You can safely ignore it

**Comment by Maelstrome26** [comment]
I've not implemented API key auth yet, and will probably still use query strings to pass them. I may use post variables at some point but I'll try to maintain compatibility in that sense. I'll let you know if anything changes.

**Comment by Maelstrome26** [comment]
Also how are you getting the map information? I don't see in your recent commit the 2nd API call? If you didn't get round to that then my bad.

**Comment by kurtextrem** [comment]
Haven't implemented yet, as I wasn't sure whether I want to do all the
queries on the server or on the client, as you cache anyway?

**Comment by Maelstrome26** [comment]
It's up to you, it should have little impact on me anyway since everything will be hitting Redis then. I would prefer if you still cache it and then ping the API when you need to, but if that's a major ballache then clients could as well.

Although having said that it does bring me back PTSD of when we had that friendly DDoS due to the amount of requests :P

**Comment by kurtextrem** [comment]
Yeah, can still remember it :D

Well, I guess I'll do the requests then, as I parse the JSON anyway.

**Comment by kurtextrem** [comment]
Published version 0.9.9: https://github.com/kurtextrem/PS2Alerts/releases/tag/0.9.9

**Comment by kurtextrem** [comment]
It seems like the facility alert is back, am I right?

**Comment by Maelstrome26** [comment]
I don't think the facility alerts are back no, I've not heard about them.

I've explained what ResultTimeType is above.

ResultAlertType is pretty simple:

```
1 = Indar
2 = Amerish?
3 = Esamir
4 = Hossin
``` 

It was yet another throwback from the days we have facility alerts, where one was an hour and the other global ones were two hours. You can safely ignore the field.

Defence is when a facility is defended, where a point can be flipped towards the enemy then flipped back, which when it's fully secure counts as a defence.

**Comment by kurtextrem** [comment]
Oh my bad, thank you!

Hm, I don't quite understand. So the alert is about territory, but somehow connected to (one) facility?

**Comment by Maelstrome26** [comment]
I'm not sure how you're getting to that conclusion? Is it the map API that's causing you problems?

**Comment by Maelstrome26** [comment]
If you can post what data you're getting I'll let you know if it's right. I'm still fiddling with the API, it's entirely possible I've broken it :P

**Comment by kurtextrem** [comment]
`{"dataID":2703980,"resultID":17521,"timestamp":1451750265,"facilityID":242,"facilityOwner":1,"facilityOldOwner":1,"durationHeld":1869,"defence":1,"controlVS":32,"controlNC":26,"controlTR":41,"zone":2,"world":25,"outfitCaptured":37533337088197545}}`
There :)

**Comment by Maelstrome26** [comment]
Is that the only record returning?

**Comment by kurtextrem** [comment]
No, but it's the data I get back when I call the API with the result id.
Like I don't understand why a facility is relevant when the alert is about territory.

**Comment by Maelstrome26** [comment]
Ok so the map API is returning the raw data from the Map table I have on the alert.

Each facility capture / defence is logged to this table. Therefore, the endpoint is returning all facility captures and defences with that alert.

Note: `ControlVS` /NC/TR etc. They signify the current territory % for each faction at the time the facility was captured. That's what you'll need in order to represent current status.

You'd need to read the very last record that's returned there and read the Control %s on them, and use that as your territory bar in the extension.

**Comment by kurtextrem** [comment]
That is what the extension does, so everything is fine. I just wanted to know if the facility is relevant to the alert or not :-)

**Comment by Maelstrome26** [comment]
You could actually use that information, saying "Last Captured: Hvar". If you know Census, you should be able to get a list of the facility names. If not I can try and provide you a dump of them all.

**Comment by Maelstrome26** [comment]
Fyi there may be a bug on my end currently with InProgress alerts, I'm in the belief they're currently being cached.

https://github.com/Maelstrome26/ps2alerts-api/issues/5 - For tracking.

**Comment by Maelstrome26** [comment]
I've implemented HTTPS & SSL for the API, but also still offer the standard unencrypted HTTP version. Please let me know if there are any issues. I highly recommend to change the API URL to https :-)

**Comment by kurtextrem** [comment]
I don't think my server supports that via file_get_contents, but I can try.

**Comment by Maelstrome26** [comment]
API breakage incoming, fundamental concepts have changed, and is likely to break things. I'll try to fix as soon as I can.

**Comment by Maelstrome26** [comment]
API Breakage has been rectified, but field names have been changed. Example request and response below:

### Request:

`GET http://api.ps2alerts.com/v2/alerts/active` - hasn't changed

### Response:
```
{
  "data": [
    {
      "id": 18223,
      "started": 1452994833,
      "ended": 0,
      "server": 1000,
      "zone": 4,
      "winner": "",
      "isDraw": false,
      "isDomination": false,
      "isValid": true,
      "inProgress": true
    },
    {
      "id": 18225,
      "started": 1452995528,
      "ended": 0,
      "server": 17,
      "zone": 2,
      "winner": "",
      "isDraw": false,
      "isDomination": false,
      "isValid": true,
      "inProgress": true
    }
  ]
}
```

However, there is a VERY nice new feature, which is data resolution. 

Simply append ?embed=maps to the end of the url, and it will resolve map data for you. I love it!

Example response (very long this):

```
{
  "data": [
    {
      "id": 18223,
      "started": 1452994833,
      "ended": 0,
      "server": 1000,
      "zone": 4,
      "winner": "",
      "isDraw": false,
      "isDomination": false,
      "isValid": true,
      "inProgress": true,
      "maps": {
        "data": [
          {
            "timestamp": 1452994875,
            "facilityID": 303010,
            "facilityNewFaction": 3,
            "facilityOldFaction": 1,
            "durationHeld": 7167,
            "controlVS": 51,
            "controlNC": 32,
            "controlTR": 14,
            "server": 1000,
            "zone": 4,
            "outfitCaptured": 0,
            "isDefence": false
          },
          {
            "timestamp": 1452994901,
            "facilityID": 287000,
            "facilityNewFaction": 3,
            "facilityOldFaction": 3,
            "durationHeld": 18307,
            "controlVS": 51,
            "controlNC": 32,
            "controlTR": 14,
            "server": 1000,
            "zone": 4,
            "outfitCaptured": 0,
            "isDefence": true
          },

**Comment by kurtextrem** [comment]
Sounds great!
Do you think it is useful to have combat stats displayed for the alert?

**Comment by kurtextrem** [comment]
And it seems like the alert type is gone, is that right? Why?

**Comment by Maelstrome26** [comment]
The combat stats are your call really. 

The type is gone for now as there is only one type of alert, which is a territory alert. The ReaultAlertType field was essentially useless and I'll be removing it in the future. It was another throwback from the days of when we had facility alerts.

**Comment by kurtextrem** [comment]
Let's see if I can come up with a use :)

Okay I see, I've also removed it from 1.0.1 - just wanted to be sure I'm not missing something.

**Comment by Maelstrome26** [comment]
Ok from now on the `Alerts/Active` endpoint shouldn't be changing much, I'll open another issue if an API breakage occurs but I don't foresee any further breakages for some time (hopefully).
