### ISSUE TITLE
Investigate perf issue

### ISSUE THREAD

**Issue by kurtextrem** [kurtextrem/PS2Alerts#25]
The popup opens very slowly for me, but I can't see the reason for that (especially as there wasn't any huge rendering change)

@Maelstrome26: Have you noticed any issues like that in the past with the extension (when the data flow was working)?

**Comment by Maelstrome26** [comment]
The opening of the popup seems OK for me. 

Ideally you could just render a "placeholder" for each server and have a loading animation over the top while it loads, similar to Facebook and how they do that on the news feed when they're loading stuff in.

**Comment by kurtextrem** [comment]
Yeah right, that is a good idea! Although I don't know why it takes so long, it seems that native extension APIs block the DOMContentLoaded event... and the popup opens when that got fired.

**Comment by Maelstrome26** [comment]
You'll also have to factor in the time it takes for my API to return back to you, which dependant on load could be anywhere from 300ms to 2 seconds or greater, per request 

So at worst case scenario, say each request takes 2 seconds, you're looking at least 6 seconds, assuming you make 3 API calls:

1. To get the active alerts 
2. To get the alert details 
3. To get the alert map state

**Comment by Maelstrome26** [comment]
That could also apply to calls to your server from the extension as well, depending how you're sending data back ofc :)

**Comment by kurtextrem** [comment]
Well, the cronjob updates the data every 60 sec on my server. Then the extension's background fetches the stored json file every 60 seconds and is completely decoupled from the popup (UI).
It seems the storage is rather slow (as background stores the data in the storage) - or only slow in the latest builds of Chrome.

**Comment by Maelstrome26** [comment]
Hmm, well that's a bit beyond my capabilities unfortunately. If you need things testing though let me know :-)

**Comment by kurtextrem** [comment]
It seems like the background page has something to do with it. Whenever the bg page is active, the main popup opens only delayed or doesn't even open at all.
When the bg page is inactive, the popup is fast enough.

**Comment by kurtextrem** [comment]
I guess I should cache the output html instead of rendering every time. But let's see how it works for others first (v 0.9.9)

**Comment by Maelstrome26** [comment]
This no longer seems to be an issue, it's pretty responsive for me.

**Comment by kurtextrem** [comment]
It's still an issue for me... so I assume it's a Dev Channel issue or whatever.
Great to know, thanks!
