### ISSUE TITLE
Seeing "Unknown" and "undefined" servers in the list

### ISSUE THREAD

**Issue by Maelstrome26** [kurtextrem/PS2Alerts#26]
Not entirely sure why it's showing up like this:

[Example](http://puu.sh/mbmg1/cd873cb1a9.png)

**Comment by kurtextrem** [comment]
That is what your API is returning currently.

**Comment by Maelstrome26** [comment]
Oh dear, let me investigate.

**Comment by Maelstrome26** [comment]
So I've just done a call to the active endpoint, got this back:

```
[
  {
    "ResultID": 17348,
    "instanceID": 1234,
    "ResultStartTime": 1450760220,
    "ResultEndTime": null,
    "ResultDateTime": null,
    "ResultServer": 1000,
    "ResultTimeType": "PRI",
    "ResultMajority": null,
    "ResultWinner": "",
    "ResultDraw": null,
    "ResultAlertCont": 2,
    "ResultAlertType": 1,
    "ResultDomination": null,
    "Valid": null,
    "InProgress": 1,
    "event": 0
  },
  {
    "ResultID": 17349,
    "instanceID": 1228,
    "ResultStartTime": 1450760453,
    "ResultEndTime": null,
    "ResultDateTime": null,
    "ResultServer": 2000,
    "ResultTimeType": "MOR",
    "ResultMajority": null,
    "ResultWinner": "",
    "ResultDraw": null,
    "ResultAlertCont": 8,
    "ResultAlertType": 2,
    "ResultDomination": null,
    "Valid": null,
    "InProgress": 1,
    "event": 0
  },
  {
    "ResultID": 17350,
    "instanceID": 6554,
    "ResultStartTime": 1450761128,
    "ResultEndTime": null,
    "ResultDateTime": null,
    "ResultServer": 1,
    "ResultTimeType": "PRI",
    "ResultMajority": null,
    "ResultWinner": "",
    "ResultDraw": null,
    "ResultAlertCont": 8,
    "ResultAlertType": 2,
    "ResultDomination": null,
    "Valid": null,
    "InProgress": 1,
    "event": 0
  }
]
```

Is this in the format you're expecting?

**Comment by Maelstrome26** [comment]
I was assuming that you'd be populating the server list with a predefined array, and populate based on information received from that endpoint.

It seems you're missing the PS4 servers, from when I looked at it a few months ago. I can provide you with the IDs if you'd like?

**Comment by kurtextrem** [comment]
Huh, only 3 servers are left active?

Would be great if you could bring me up to date, haven't been following PS2
too much in the past.
Am 28.12.2015 16:01 schrieb "Matthew Cavanagh" <notifications@github.com>:

**Comment by Maelstrome26** [comment]
Ahh I see the misunderstanding, I'm only returning alerts that are active.

So, the default is that there is no alert on any server, unless they are shown in that list. Sorry, I should have mentioned that very key point.

Here is a list of the current servers:

PC:
```
1: Connery
10: Miller
13: Cobalt
17: Emerald
19: Jaeger (event server)
25: Briggs
```

PS4:
```
1000: 'Genudine (PS4US)'
1001: 'Palos (PS4US)'
1002: 'Crux (PS4US)'
1003: 'Searhus (PS4US)'
1004: 'Xelas (PS4US)'
2000: 'Ceres (PS4EU)'
2001: 'Lithcorp (PS4EU)'
2002: 'Rashnu (PS4EU)'
```

**Comment by Maelstrome26** [comment]
My suggestion would be to list each server by building elements with a loop with the details above, then activating each server based on the information provided by the Active endpoint.

**Comment by kurtextrem** [comment]
Ahh thank you. Yeah, I will do so.
Am 28.12.2015 16:17 schrieb "Matthew Cavanagh" <notifications@github.com>:

**Comment by Maelstrome26** [comment]
Just got an updated list of currently active servers, apparently PS4 has had some merges:

```
1: 'Connery',
10: 'Miller',
17: 'Emerald',
19: 'Jaeger',
25: 'Briggs',
1000: 'Genudine',
2000: 'Ceres'
```

**Comment by kurtextrem** [comment]
Updated!

**Comment by Maelstrome26** [comment]
Still seeing undefined servers.

http://puu.sh/mgUBC/a73ab84958.png

**Comment by kurtextrem** [comment]
Hm. I guess the data is faulty now for some people. Can you try a clean install?

**Comment by Maelstrome26** [comment]
I can give it a go :-)

**Comment by Maelstrome26** [comment]
Yup, reinstall fixed this. Only showing PC servers though, is that intentional?

**Comment by kurtextrem** [comment]
Yes, but there is a setting in the options :)

**Comment by Maelstrome26** [comment]
Ahh I see. Now it's returning all the dead PS4 Servers :-/

And I've just seen it return a undefined server again.

**Comment by Maelstrome26** [comment]
On v0.993:

http://puu.sh/mgYfS/ad06d49cd1.png

**Comment by kurtextrem** [comment]
Hm... I guess I have to clear the sync storage.

**Comment by Maelstrome26** [comment]
No longer seeing this. Seems to be fixed.
