### ISSUE TITLE
"View this alert live" links to undefined

### ISSUE THREAD

**Issue by Maelstrome26** [kurtextrem/PS2Alerts#45]
Also linking incorrectly. 

Currently showing: `http://ps2alerts.com/Alert/Undefined`

Ideally should be: `http://www.ps2alerts.com/alert/12345`

**Comment by kurtextrem** [comment]
Done. Is there any substitute for http://ps2alerts.com/allalerts?

**Comment by Maelstrome26** [comment]
Yes, http://www.ps2alerts.com/alert-history

**Comment by Maelstrome26** [comment]
:+1:
